Math087 - Mathematical Modeling
===============================
[Tufts University](http://www.tufts.edu) -- [Department of Math](http://math.tufts.edu)  
[Arkadz Kirshtein](https://math.tufts.edu/people/facultyKirshtein.htm) <arkadz.kirshtein@tufts.edu>  
*Fall 2023*

*Based on materials created by James Adler and George McNinch*

Course material (Class 11): Some practical examples
---------------------------------------------------------------

Introduction
============

Last week, we introduced some finite-state machines whose transition behavior could be described by a matrix. This week, we investigate properties of such matrices, by studying their eigenvalues and eigenvectors.

Eigen-stuff
============

Recall that a number $\lambda \in\mathbb{R}$ is an *eigenvalue* of $A \in \mathbb{R}^{n \times n}$ if there is a non-zero vector $\mathbf{v} \in \mathbb{R}^n$ for which
$$A \mathbf{v} = \lambda \mathbf{v};$$
$\mathbf{v}$ is then called an *eigenvector*.

If $A$ is diagonal -- e.g. if 

$$A = \begin{bmatrix}
\lambda_1 & 0 & 0 & 0 \\
0 & \lambda_2 & 0 & 0 \\
0 & 0 & \lambda_3 & 0  \\
0 & 0 & 0 & \lambda_4 \\
\end{bmatrix} =\operatorname{diag}(\lambda_1,\lambda_2,\lambda_3,\lambda_4)$$

-- it is easy to see that each standard basis vector $\mathbf{e}_i$
is an eigenvector, with corresponding eigenvalue $\lambda_i$ (the $(i,i)$-the entry of $A$).

Diagonalizable matrices
=======================

Now suppose that $A$ is an $n\times n$ matrix, that
$\mathbf{v}_1,\dots,\mathbf{v}_n$ are eigenvectors for $A$, and that
$\lambda_1,\dots,\lambda_n$ are the corresponding eigenvalues.
Write
$$P = \begin{bmatrix} \mathbf{v}_1 & \cdots & \mathbf{v}_n \end{bmatrix}$$
for the matrix whose columns are the $\mathbf{v}_i$.

**Theorem**: If the eigenvectors $\mathbf{v}_1,\dots,\mathbf{v}_n$
are linearly independent -- equivalently, if the matrix $P$ is invertible -- then 
$$P^{-1} A P = \begin{bmatrix}
\lambda_1 & 0 & 0 & 0 \\
0 & \lambda_2 & 0 & 0 \\
\vdots & \vdots & \ddots & \vdots  \\
0 & 0 & 0 & \lambda_n \\
\end{bmatrix} = \operatorname{diag}(\lambda_1,\dots,\lambda_n)$$
i.e. $P^{-1} A P$ is the diagonal matrix $n \times n$ matrix whose diagonal entries
are $\lambda_1,\dots,\lambda_n$.

---------------

Diagonalizable matrices & power iteration
=========================================
**Theorem**: Let $A$ be a diagonalizable $n \times n$, with $n$ linearly independent eigenvectors $\mathbf{v}_1,\dots,\mathbf{v}_n$
with corresponding eigenvalues $\lambda_1,\dots,\lambda_n$.
As before, write

$$P = \begin{bmatrix} 
\mathbf{v}_1 & \cdots & \mathbf{v}_n 
\end{bmatrix}.$$

**a)** Suppose $|\lambda_i| <1$ for all $i$. Then $A^m \to \mathbf{0}$ as $m \to \infty$.

**b)** Suppose that $\lambda_1 = 1$, and $|\lambda_i| <1$ for $2 \le i \le n$. 
Any vector $\mathbf{v} \in \mathbb{R}^n$ may be written

$$\mathbf{v} = \sum_{i=1}^n c_i \mathbf{v}_i.$$

If $c_1 \ne 0$, then 
$$A^m \mathbf{v} = c_1\mathbf{v}_1 
\quad \text{as} \quad m \to \infty.$$

If $c_1 = 0$ then
$$A^m \mathbf{v} =  \mathbf{0}
\quad \text{as} \quad m \to \infty.$$

Corollary
---------

Suppose that $A$ is diagonalizable with eigenvalues $\lambda_1,\dots,\lambda_n$, that
$\lambda_1 = 1$, and that $|\lambda_i| < 1$ for $i =2,...,n$.
Let $\mathbf{v_1}$ be a 1-eigenvector for $A$.

Then 

$$A^m \to B \quad \text{as $m \to \infty$}$$

for a matrix $B$ with the property that each column of $B$ is either $\mathbf{0}$
or some multiple of $\mathbf{v_1}$.

----------------

Stochastic Matrices
====================

A vector $\mathbf{v} = \begin{bmatrix} v_1 & v_2 & \cdots & v_n \end{bmatrix}^T \in \mathbb{R}^n$ will be said to be a *probability vector* if
all of its entries $v_i$ satisfy $v_i \ge 0$ and if
$$\begin{bmatrix} 1 & 1 & \cdots & 1 \end{bmatrix} \cdot \mathbf{v} = \sum_{i=1}^n v_i = 1.$$

Let $A = \begin{bmatrix} a_{ij} \end{bmatrix} \in \mathbb{R}^{n \times n}$. We say that $A$ is a *stochastic matrix* if $a_{ij} \ge 0$ for all $i,j$ and if
$$\begin{bmatrix} 1 & 1 & \cdots & 1 \end{bmatrix} \cdot A = \begin{bmatrix} 1 &  1 &  \cdots & 1 \end{bmatrix};$$
in words, $A$ is a stochastic matrix if each column of $A$ is a probability vector.


**Proposition:** Let $A$ be a stochastic matrix.  
**a)** $A$ has an eigenvector with eigenvalue 1.  
**b)** Let $\lambda$ be any eigenvalue of a $A$.  Then $|\lambda| \le 1$.  
**c)** If $\mathbf{w}$ is an eigenvector of $A$ with eigenvalue $\lambda$ satisfying
$\lambda \ne 1$ then $\begin{bmatrix} 1 & 1 & \cdots & 1 \end{bmatrix} \mathbf{w} = 0$.

**Corollary:**
Suppose that the stochastic matrix $A$ is diagonalizable, and that  the *1-eigenspace* of $A$ has dimension 1. Let $\mathbf{v}$ be an eigenvector for $A$ with eigenvalue 1, and set $c = \begin{bmatrix} 1 & 1 & \cdots & 1 \end{bmatrix} \mathbf{v}$.
Then $\mathbf{w} = \dfrac{\mathbf{v}}{c}$ is a probability vector, and

$$A^m \to B \quad \text{as $m \to \infty$}$$

for a stochastic matrix $B$. Each column of $B$ is equal to $\mathbf{w}$.

------

**Theorem: (Perron-Frobenius)** Let $G$ be a transition diagram for a Markov chain, and suppose that $G$ is strongly connected and aperiodic. Let $P$ be the corresponding stochastic matrix. The multiplicity of the eigenvalue $\lambda = 1$ for $P$ is 1 -- i.e.

$$\dim \operatorname{Null}(P-I_n) = 1.$$

All other eigenvalues $\lambda$ satisfy $|\lambda|  < 1$.

There is a $1$-eigenvector $\mathbf{v}$ which is a probability vector.

--------------

In [1]:
import numpy as np

from numpy.random import default_rng

from numpy.linalg import eig, matrix_power

rng = default_rng()

def rand_stoch(n):
    v=np.array([rng.random(n) for i in range(n)])
    # v=rng.random((n,n)) # same result
    f=np.ones(n)@v
    return (1/f)*v


In [2]:
T=rand_stoch(8)
print(T)
np.ones(8)@T

[[5.25932892e-02 1.77044928e-01 1.55607615e-01 2.53402677e-01
  1.45677335e-01 9.40023084e-02 1.13830721e-01 1.19067307e-01]
 [1.63737874e-01 2.01543248e-01 4.03224704e-02 1.45555294e-01
  6.91382744e-02 1.98931600e-01 6.14108444e-02 2.32806019e-01]
 [1.50623835e-01 4.60799214e-03 1.78584447e-01 2.66747550e-01
  2.14934984e-01 1.47594303e-01 1.07402729e-01 2.02231998e-01]
 [1.42718348e-01 2.44577378e-01 1.42572931e-01 7.58966520e-02
  1.49968956e-01 7.94383403e-02 1.66537035e-01 6.52587504e-02]
 [4.12951328e-02 1.81460549e-04 1.77085595e-01 3.04433322e-02
  7.17084568e-03 1.92964341e-01 5.22106411e-02 4.20653284e-02]
 [1.62226650e-01 2.56516631e-01 8.73877318e-02 1.33102083e-01
  4.36348297e-02 1.61871222e-01 1.88236187e-01 1.12059225e-02]
 [1.43934703e-01 7.18374899e-02 1.26745142e-01 6.13856761e-02
  1.59508903e-01 1.30577575e-02 1.46431633e-01 1.97020616e-01]
 [1.42870168e-01 4.36908736e-02 9.16940676e-02 3.34667364e-02
  2.09965871e-01 1.12140129e-01 1.63940209e-01 1.30344059e-01]]

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
e_vals,e_vecs = eig(T)

In [4]:
e_vals

array([ 1.        +0.j        ,  0.20742554+0.j        ,
       -0.13656183+0.07117379j, -0.13656183-0.07117379j,
       -0.1019428 +0.j        ,  0.10555982+0.j        ,
        0.00825825+0.13460686j,  0.00825825-0.13460686j])

In [5]:
w=e_vecs[:,0]
v = (1/(np.ones(8)@w))*w
np.real(v)

array([0.13965469, 0.14157466, 0.15511433, 0.1342152 , 0.07468989,
       0.1376896 , 0.10912701, 0.10793462])

In [6]:
vv=(matrix_power(T,200)[:,0])

In [7]:
vv

array([0.13965469, 0.14157466, 0.15511433, 0.1342152 , 0.07468989,
       0.1376896 , 0.10912701, 0.10793462])

In [8]:
v-vv < 1e-7*np.ones(8)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
(v-vv < 1e-7*np.ones(8)).all()

True

How to rank-order the entries in  a vector??
---------------------------------------------

Python can sort -- but sometimes you don't just want the sorted values.


In [10]:
vv

array([0.13965469, 0.14157466, 0.15511433, 0.1342152 , 0.07468989,
       0.1376896 , 0.10912701, 0.10793462])

In [11]:
ll = [(i,vv[i]) for i in range(8)]
ll

[(0, 0.13965469144042364),
 (1, 0.14157465811218395),
 (2, 0.1551143257249531),
 (3, 0.1342151998141175),
 (4, 0.07468988966967852),
 (5, 0.1376896038569325),
 (6, 0.10912701427389195),
 (7, 0.10793461710781899)]

In [12]:
ll.sort(key=lambda x:(-1)*x[1])

In [13]:
ll

[(2, 0.1551143257249531),
 (1, 0.14157465811218395),
 (0, 0.13965469144042364),
 (5, 0.1376896038569325),
 (3, 0.1342151998141175),
 (6, 0.10912701427389195),
 (7, 0.10793461710781899),
 (4, 0.07468988966967852)]

In [14]:
def top_ten(n,it):
    T=rand_stoch(n)
    vv=matrix_power(T,it)[:,0]
    ll=[(i,vv[i]) for i in range(n)]
    ll.sort(key=lambda x:(-1)*x[1])
    iter_string = "\n".join([f"{l[0]:3d} - {l[1]:.5f}" for l in ll[0:10]])
    
    e_vals,e_vecs = eig(T)
    w=e_vecs[:,0]
    ww = (1/(np.ones(n)@w))*w
    kl=[(i,ww[i]) for i in range(n)]
    kl.sort(key=lambda x:(-1)*x[1])
    eig_string = "\n".join([f"{l[0]:3d} - {l[1]:.5f}" for l in kl[0:10]])
    
    return iter_string + "\n\n" + eig_string

In [15]:
print(top_ten(50,2))

 30 - 0.02429
 21 - 0.02340
 14 - 0.02338
 24 - 0.02322
 23 - 0.02313
  6 - 0.02230
 47 - 0.02215
  2 - 0.02203
 26 - 0.02201
 31 - 0.02161

 30 - 0.02302+0.00000j
 17 - 0.02296+0.00000j
 23 - 0.02293+0.00000j
 21 - 0.02222+0.00000j
 26 - 0.02211+0.00000j
 14 - 0.02209+0.00000j
  6 - 0.02201+0.00000j
 22 - 0.02188+0.00000j
  2 - 0.02172+0.00000j
 18 - 0.02171+0.00000j
